export const degreeList = [
    { value: "Accounting MMA", label: "Accounting MMA", College: "Business" },
    { value: "Accounting PhD", label: "Accounting PhD", College: "Business" },
    { value: "Advertising Public Relations MA", label: "Advertising Public Relations MA", College: "Communication and Information Sciences" },
    { value: "Aerospace Engineering and Mechanics MSAEM", label: "Aerospace Engineering and Mechanics MSAEM", College: "Engineering" },
    { value: "Aerospace Engineering and Mechanics PhD", label: "Aerospace Engineering and Mechanics PhD", College: "Engineering" },
    { value: "American Studies MA", label: "American Studies MA", College: "Arts and Sciences" },
    { value: "Anthropology MA", label: "Anthropology MA", College: "Arts and Sciences" },
    { value: "Anthropology PhD", label: "Anthropology PhD", College: "Arts and Sciences" },
    { value: "Applied Mathematics PhD", label: "Applied Mathematics PhD", College: "Arts and Sciences" },
    { value: "Applied Statistics MS", label: "Applied Statistics MS", College: "Business" },
    { value: "Applied Statistics PhD", label: "Applied Statistics PhD", College: "Business" },
    { value: "Archival Studies CRT", label: "Archival Studies CRT", College: "Communication and Information Sciences" },
    { value: "Art History MA", label: "Art History MA", College: "Arts and Sciences" },
    { value: "Athletic Training MS", label: "Athletic Training MS", College: "Human Environmental Sciences" },
    { value: "Biological Sciences MA", label: "Biological Sciences MA", College: "Arts and Sciences" },
    { value: "Biology MS", label: "Biology MS", College: "Arts and Sciences" },
    { value: "Biology PhD", label: "Biology PhD", College: "Arts and Sciences" },
    { value: "Book Arts CRT", label: "Book Arts CRT", College: "Communication and Information Sciences" },
    { value: "Book Arts MFA", label: "Book Arts MFA", College: "Communication and Information Sciences" },
    { value: "Business Administration EMBA", label: "Business Administration EMBA", College: "Business" },
    { value: "Business Administration MBA", label: "Business Administration MBA", College: "Business" },
    { value: "Business Analytics MS", label: "Business Analytics MS", College: "Business" },
    { value: "Chemical Engineering MCE", label: "Chemical Engineering MCE", College: "Engineering" },
    { value: "Chemical Engineering PhD", label: "Chemical Engineering PhD", College: "Engineering" },
    { value: "Chemistry MSC", label: "Chemistry MSC", College: "Arts and Sciences" },
    { value: "Chemistry PhD", label: "Chemistry PhD", College: "Arts and Sciences" },
    { value: "Civil Engineering MCV", label: "Civil Engineering MCV", College: "Engineering" },
    { value: "Civil Engineering PhD", label: "Civil Engineering PhD", College: "Engineering" },
    { value: "College Teaching CRT", label: "College Teaching CRT", College: "Education" },
    { value: "Communication & Information Sciences PhD", label: "Communication & Information Sciences PhD", College: "Communication and Information Sciences" },
    { value: "Communication Studies MA", label: "Communication Studies MA", College: "Communication and Information Sciences" },
    { value: "Computer Science MSCS", label: "Computer Science MSCS", College: "Engineering" },
    { value: "Computer Science PhD", label: "Computer Science PhD", College: "Engineering" },
    { value: "Conflict Resolution CRT", label: "Conflict Resolution CRT", College: "Human Environmental Sciences" },
    { value: "Consumer Sciences MS", label: "Consumer Sciences MS", College: "Human Environmental Sciences" },
    { value: "Counselor Education EDS", label: "Counselor Education EDS", College: "Education" },
    { value: "Counselor Education PhD", label: "Counselor Education PhD", College: "Education" },
    { value: "Counselor Education-Clinical Mental Health Counseling MA", label: "Counselor Education-Clinical Mental Health Counseling MA", College: "Education" },
    { value: "Counselor Education-Rehabilitation Counseling MA", label: "Counselor Education-Rehabilitation Counseling MA", College: "Education" },
    { value: "Counselor Education-School Counseling MA", label: "Counselor Education-School Counseling MA", College: "Education" },
    { value: "Creative Writing MFA", label: "Creative Writing MFA", College: "Arts and Sciences" },
    { value: "Criminology & Criminal Justice MS", label: "Criminology & Criminal Justice MS", College: "Arts and Sciences" },
    { value: "Curriculum and Instruction EDD", label: "Curriculum and Instruction EDD", College: "Education" },
    { value: "Curriculum and Instruction PHD", label: "Curriculum and Instruction PHD", College: "Education" },
    { value: "Dance MFA", label: "Dance MFA", College: "Arts and Sciences" },
    { value: "Digital Communication CRT", label: "Digital Communication CRT", College: "Communication and Information Sciences" },
    { value: "Economics (Quantitative) MA", label: "Economics (Quantitative) MA", College: "Business" },
    { value: "Economics (Quantitative) PHD", label: "Economics (Quantitative) PHD", College: "Business" },
    { value: "Educational Leadership EDD", label: "Educational Leadership EDD", College: "Education" },
    { value: "Educational Leadership EDS", label: "Educational Leadership EDS", College: "Education" },
    { value: "Educational Leadership MA", label: "Educational Leadership MA", College: "Education" },
    { value: "Educational Leadership PhD", label: "Educational Leadership PhD", College: "Education" },
    { value: "Educational Psychology EDS", label: "Educational Psychology EDS", College: "Education" },
    { value: "Educational Psychology MA", label: "Educational Psychology MA", College: "Education" },
    { value: "Educational Psychology PhD", label: "Educational Psychology PhD", College: "Education" },
    { value: "Educational Research PhD", label: "Educational Research PhD", College: "Education" },
    { value: "Electrical Engineering MSEE", label: "Electrical Engineering MSEE", College: "Engineering" },
    { value: "Electrical Engineering PhD", label: "Electrical Engineering PhD", College: "Engineering" },
    { value: "Elementary Education EDS", label: "Elementary Education EDS", College: "Education" },
    { value: "Elementary Education MA", label: "Elementary Education MA", College: "Education" },
    { value: "English MA", label: "English MA", College: "Arts and Sciences" },
    { value: "English PhD", label: "English PhD", College: "Arts and Sciences" },
    { value: "English as a Second Language MA", label: "English as a Second Language MA", College: "Arts and Sciences" },
    { value: "Environmental Engineering MS", label: "Environmental Engineering MS", College: "Engineering" },
    { value: "Family Nurse Practitioner CRT", label: "Family Nurse Practitioner CRT", College: "Human Environmental Sciences" },
    { value: "Finance MS", label: "Finance MS", College: "Business" },
    { value: "Finance PhD", label: "Finance PhD", College: "Business" },
    { value: "Geographic Information Systems CRT", label: "Geographic Information Systems CRT", College: "Arts and Sciences" },
    { value: "Geography MS", label: "Geography MS", College: "Arts and Sciences" },
    { value: "Geography PhD", label: "Geography PhD", College: "Arts and Sciences" },
    { value: "Geology MS", label: "Geology MS", College: "Arts and Sciences" },
    { value: "Geology PhD", label: "Geology PhD", College: "Arts and Sciences" },
    { value: "German MA", label: "German MA", College: "Arts and Sciences" },
    { value: "Health Education & Promotion MPH", label: "Health Education & Promotion MPH", College: "Human Environmental Sciences" },
    { value: "Health Education & Promotion PhD", label: "Health Education & Promotion PhD", College: "Human Environmental Sciences" },
    { value: "Health Studies MA", label: "Health Studies MA", College: "Human Environmental Sciences" },
    { value: "Higher Education Administration EDD", label: "Higher Education Administration EDD", College: "Education" },
    { value: "Higher Education Administration MA", label: "Higher Education Administration MA", College: "Education" },
    { value: "Higher Education Administration PhD", label: "Higher Education Administration PhD", College: "Education" },
    { value: "History MA", label: "History MA", College: "Arts and Sciences" },
    { value: "History PhD", label: "History PhD", College: "Arts and Sciences" },
    { value: "Hospitality Management MS", label: "Hospitality Management MS", College: "Human Environmental Sciences" },
    { value: "Human Development and Family Studies MS", label: "Human Development and Family Studies MS", College: "Human Environmental Sciences" },
    { value: "Human Environmental Sciences MHS", label: "Human Environmental Sciences MHS", College: "Human Environmental Sciences" },
    { value: "Human Nutrition MS", label: "Human Nutrition MS", College: "Human Environmental Sciences" },
    { value: "Human Nutrition PhD", label: "Human Nutrition PhD", College: "Human Environmental Sciences" },
    { value: "Instructional Leadership EDD", label: "Instructional Leadership EDD", College: "Education" },
    { value: "Instructional Leadership PhD", label: "Instructional Leadership PhD", College: "Education" },
    { value: "Instructional Technology CRT", label: "Instructional Technology CRT", College: "Education" },
    { value: "Instructional Technology MA", label: "Instructional Technology MA", College: "Education" },
    { value: "Interdisciplinary MA", label: "Interdisciplinary MA", College: "Graduate Interdisciplinary Studies" },
    { value: "Interdisciplinary MS", label: "Interdisciplinary MS", College: "Graduate Interdisciplinary Studies" },
    { value: "Interdisciplinary PhD", label: "Interdisciplinary PhD", College: "Graduate Interdisciplinary Studies" },
    { value: "Journalism and Media Studies MA", label: "Journalism and Media Studies MA", College: "Communication and Information Sciences" },
    { value: "Kinesiology MA", label: "Kinesiology MA", College: "Education" },
    { value: "Kinesiology PhD", label: "Kinesiology PhD", College: "Education" },
    { value: "Library and Information Studies MLIS", label: "Library and Information Studies MLIS", College: "Communication and Information Sciences" },
    { value: "Literacy Research, Theory & Pedagogy CRT", label: "Literacy Research, Theory & Pedagogy CRT", College: "Education" },
    { value: "Management Information Systems MS", label: "Management Information Systems MS", College: "Business" },
    { value: "Management MA", label: "Management MA", College: "Business" },
    { value: "Management PhD", label: "Management PhD", College: "Business" },
    { value: "Marine Science MS", label: "Marine Science MS", College: "Arts and Sciences" },
    { value: "Marketing MS", label: "Marketing MS", College: "Business" },
    { value: "Marketing PhD", label: "Marketing PhD", College: "Business" },
    { value: "Master's Entry to the Profession of Nursing MSN", label: "Master's Entry to the Profession of Nursing MSN", College: "Nursing" },
    { value: "Materials Metallurgical Engineering PhD", label: "Materials Metallurgical Engineering PhD", College: "Engineering" },
    { value: "Materials Science PhD", label: "Materials Science PhD", College: "Graduate Interdisciplinary Studies" },
    { value: "Mathematics MA", label: "Mathematics MA", College: "Arts and Sciences" },
    { value: "Mathematics PhD", label: "Mathematics PhD", College: "Arts and Sciences" },
    { value: "Mechanical Engineering MSME", label: "Mechanical Engineering MSME", College: "Engineering" },
    { value: "Mechanical Engineering PhD", label: "Mechanical Engineering PhD", College: "Engineering" },
    { value: "Metallurgical Engineering MS", label: "Metallurgical Engineering MS", College: "Engineering" },
    { value: "Museum Studies CRT", label: "Museum Studies CRT", College: "Arts and Sciences" },
    { value: "Music DMA", label: "Music DMA", College: "Arts and Sciences" },
    { value: "Music MM", label: "Music MM", College: "Arts and Sciences" },
    { value: "Non-Degree Arts & Sciences Student", label: "Non-Degree Arts & Sciences Student", College: "Arts and Sciences" },
    { value: "Non-Degree Business Student", label: "Non-Degree Business Student", College: "Business" },
    { value: "Non-Degree Business Student (Distance Learning)", label: "Non-Degree Business Student (Distance Learning)", College: "Business" },
    { value: "Non-Degree Communication & Information Sciences Student", label: "Non-Degree Communication & Information Sciences Student", College: "Communication and Information Sciences" },
    { value: "Non-Degree Communication & Information Sciences Student (Distance Learning)", label: "Non-Degree Communication & Information Sciences Student (Distance Learning)", College: "Communication and Information Sciences" },
    { value: "Non-Degree Community Health Sciences Student", label: "Non-Degree Community Health Sciences Student", College: "Community Health Sciences" },
    { value: "Non-Degree Education Student", label: "Non-Degree Education Student", College: "Education" },
    { value: "Non-Degree Education Student (Distance Learning)", label: "Non-Degree Education Student (Distance Learning)", College: "Education" },
    { value: "Non-Degree Education Student Certification", label: "Non-Degree Education Student Certification", College: "Education" },
    { value: "Non-Degree Engineering Student", label: "Non-Degree Engineering Student", College: "Engineering" },
    { value: "Non-Degree Engineering Student (Distance Learning)", label: "Non-Degree Engineering Student (Distance Learning)", College: "Engineering" },
    { value: "Non-Degree Human Environmental Sciences Student", label: "Non-Degree Human Environmental Sciences Student", College: "Human Environmental Sciences" },
    { value: "Non-Degree Human Environmental Sciences Student (Distance Learning)", label: "Non-Degree Human Environmental Sciences Student (Distance Learning)", College: "Human Environmental Sciences" },
    { value: "Non-Degree Nursing Student", label: "Non-Degree Nursing Student", College: "Nursing" },
    { value: "Non-Degree Nursing Student (Distance Learning)", label: "Non-Degree Nursing Student (Distance Learning)", College: "Nursing" },
    { value: "Non-Degree Social Work Student", label: "Non-Degree Social Work Student", College: "Nursing" },
    { value: "Non-Degree Social Work Student (Distance Learning)", label: "Non-Degree Social Work Student (Distance Learning)", College: "Nursing" },
    { value: "Nursing DNP", label: "Nursing DNP", College: "Nursing" },
    { value: "Nursing MSN", label: "Nursing MSN", College: "Nursing" },
    { value: "Nursing PhD", label: "Nursing PhD", College: "Nursing" },
    { value: "Operations Management MS", label: "Operations Management MS", College: "Business" },
    { value: "Operations Management PhD", label: "Operations Management PhD", College: "Business" },
    { value: "Physics MS", label: "Physics MS", College: "Arts and Sciences" },
    { value: "Physics PhD", label: "Physics PhD", College: "Arts and Sciences" },
    { value: "Political Science MA", label: "Political Science MA", College: "Arts and Sciences" },
    { value: "Political Science PhD", label: "Political Science PhD", College: "Arts and Sciences" },
    { value: "Population Health Sciences MS", label: "Population Health Sciences MS", College: "Community Health Sciences" },
    { value: "Psychiatric Mental Health Nurse Practitioner CRT", label: "Psychiatric Mental Health Nurse Practitioner CRT", College: "Nursing" },
    { value: "Psychology PhD", label: "Psychology PhD", College: "Arts and Sciences" },
    { value: "Public Administration MPA", label: "Public Administration MPA", College: "Arts and Sciences" },
    { value: "Qualitative Research CRT", label: "Qualitative Research CRT", College: "Education" },
    { value: "Quantitative Research CRT", label: "Quantitative Research CRT", College: "Education" },
    { value: "Religion in Culture MA", label: "Religion in Culture MA", College: "Arts and Sciences" },
    { value: "Romance Languages MA", label: "Romance Languages MA", College: "Arts and Sciences" },
    { value: "Romance Languages PhD", label: "Romance Languages PhD", College: "Arts and Sciences" },
    { value: "Rural Community Health MS", label: "Rural Community Health MS", College: "Community Health Sciences" },
    { value: "School Psychology PhD", label: "School Psychology PhD", College: "Education" },
    { value: "Secondary Education EDS", label: "Secondary Education EDS", College: "Education" },
    { value: "Secondary Education MA", label: "Secondary Education MA", College: "Education" },
    { value: "Social & Cultural Studies CRT", label: "Social & Cultural Studies CRT", College: "Education" },
    { value: "Social Work DSW", label: "Social Work DSW", College: "Nursing" },
    { value: "Social Work MSW", label: "Social Work MSW", College: "Nursing" },
    { value: "Social Work PhD", label: "Social Work PhD", College: "Nursing" },
    { value: "Special Education EDD", label: "Special Education EDD", College: "Education" },
    { value: "Special Education EDS", label: "Special Education EDS", College: "Education" },
    { value: "Special Education MA", label: "Special Education MA", College: "Education" },
    { value: "Special Education PhD", label: "Special Education PhD", College: "Education" },
    { value: "Speech Language Pathology MS", label: "Speech Language Pathology MS", College: "Arts and Sciences" },
    { value: "Studio Art MA", label: "Studio Art MA", College: "Arts and Sciences" },
    { value: "Studio Art MFA", label: "Studio Art MFA", College: "Arts and Sciences" },
    { value: "Tax Accounting MTA", label: "Tax Accounting MTA", College: "Business" },
    { value: "Teaching English to Speakers of Other Languages", label: "Teaching English to Speakers of Other Languages", College: "Arts and Sciences" },
    { value: "Theatre MFA", label: "Theatre MFA", College: "Arts and Sciences" },
    { value: "Women Studies CRT", label: "Women Studies CRT", College: "Arts and Sciences" },
    { value: "Women Studies MA", label: "Women Studies MA", College: "Arts and Sciences" },
  ];

export const styles = [
    { value: 'None', label: 'Void' },
    { value: 'APA', label: 'APA' },
    { value: 'Chicago Style', label: 'Chicago Style' },
    { value: 'MLA', label: 'MLA' },
    { value: 'Turabian', label: 'Turabian' }
  ];
export const documentTypes = [
    { value: 'None', label: 'Void' },
    { value: 'Dissertation', label: 'Thesis' },
    { value: 'Thesis', label: 'Dissertation' },
  ];
export const fontList = [
    { value: 'None', label: 'Void' },
    { value: 'Arial', label: 'Arial' },
    { value: 'Century', label: 'Century' },
    { value: 'Garamond', label: 'Garamond' },
    { value: 'Georgia', label: 'Georgia'},
    { value: 'Tahoma', label: 'Tahoma' },
    { value: 'Times New Roman', label: 'Times New Roman' },
    { value: 'Veranda', label: 'Veranda' }
  ];